context:
  version: "0.1.0"

package:
  name: pyo3-rattler-build
  version: ${{ version }}

source:
  path: ../

build:
  number: 0
  script:
    - maturin build --release -o wheels
    - pip install wheels/*.whl -vv
  files:
    exclude:
      - .cargo/
      - "**/*.pyc"

requirements:
  host:
    - ${{ compiler('rust') }}
    - maturin
    - python
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - pyo3_rattler_build
      pip_check: true
  - script:
      - python -c "import pyo3_rattler_build; print(dir(pyo3_rattler_build)); print(dir(pyo3_rattler_build.sum_as_string))"

about:
  license: MIT
