name: Pixi test

on: [push]

jobs:
  build:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          manifest-path: "pyproject.toml"
          pixi-version: v0.28.2
      - run: pixi run test
