name: Pixi test

on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          manifest-path: "pyproject.toml"
          pixi-version: v0.28.2
      - run: pixi run test
